# This is a basic workflow to help you get started with Actions
name: Build the AMI after merging a PR
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      #Install Packer

      # Runs a single command using the runners shell
      - name: Add Hashicorp GPG key
        run: curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
      
      # Add official hashicorp linux repo
      - name: Add official hashicorp linux repo
        run: sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
      
      - name: Update and install
        run: sudo apt-get -y update && sudo apt-get install -y packer

      # Runs a set of commands using the runners shell
      - name: Run build AMI
        run: |
          packer validate ami_template.json
          packer build -var 'aws_access_key=${{ secrets.AWS_ACCESS_KEY }}' -var 'aws_secret_key=${{ secrets.AWS_SECRET_KEY }}' -var 'aws_region=${{ secrets.AWS_REGION }}' -var 'subnet_id=${{ secrets.AWS_SUBNET_ID }}' -var 'source_ami=${{ secrets.SOURCE_AMI }}' ami_template.json